name: Setup Google Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  setup-remote-desktop:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Google Remote Desktop Host
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chromeremotedesktophost.msi"

    - name: Install Google Remote Desktop Host
      run: |
        Start-Process msiexec.exe -ArgumentList '/i chromeremotedesktophost.msi /quiet /norestart' -NoNewWindow -Wait

    - name: Start Google Remote Desktop Host
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="123321" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME

    - name: Cleanup
      run: |
        Remove-Item "chromeremotedesktophost.msi"
