name: PowerShell Script Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-powershell:
    runs-on: windows-latest  # This will use the latest Windows Server runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PowerShell Script
        shell: pwsh  # Use PowerShell Core
        run: |
          # Your PowerShell commands go here
          Write-Host "Hello from PowerShell on GitHub Actions!"
          # Example: List files in the current directory
          Get-ChildItem
