name: Setup AnyDesk

on:
  push:
    branches:
      - main

jobs:
  setup-anydesk:
    runs-on: windows-latest

    steps:
    - name: Download AnyDesk
      run: |
        Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "AnyDesk.exe"

    - name: Install AnyDesk
      run: |
        Start-Process -FilePath "AnyDesk.exe" -ArgumentList "/S" -NoNewWindow -Wait

    - name: Set Unattended Access Password
      run: |
        & "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --set-password "123321"

    - name: Cleanup
      run: |
        Remove-Item "AnyDesk.exe" -Force
